# Generated by Django 6.0 on 2026-02-11 16:23

import apps_.sellers.validators
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('biznes_type', models.CharField(blank=True, choices=[('individual', 'Yakka tartibdagi tadbirkor'), ('entrepreneur', "O'zini o'zi band qilgan shaxs"), ('company', 'MChJ yoki boshqa yuridik shaxs')], max_length=50, null=True)),
                ('phone', models.CharField(help_text='Telefon raqami (9 ta raqam)', max_length=9, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='SellerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('holder_name', models.CharField(help_text='Hisob egasining ismi', max_length=255)),
                ('account_number', models.CharField(help_text='Hisob raqami', max_length=16, validators=[apps_.sellers.validators.validate_account_number])),
                ('bank_code', models.CharField(help_text='Bank Kodi(MFO)', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Kompaniya nomi', max_length=255)),
                ('stir', models.CharField(help_text='STIR raqami', max_length=20, unique=True)),
                ('oked', models.CharField(help_text='OKED raqami', max_length=10)),
                ('registration_certificate', models.FileField(help_text="MChJ (yoki boshqa yuridik shaxs)ni ro'yxatdan o'tkazish haqida xabarnoma yoki guvohnoma", upload_to='company/registration_certificate', validators=[apps_.sellers.validators.validate_file])),
                ('tashkilot_direktori_qarori', models.FileField(upload_to='company/tashkilot_direktori_qarori', validators=[apps_.sellers.validators.validate_file])),
                ('passport_image', models.FileField(help_text="Pasportning shaxsiy ma'lumotlar bilan sahifasi", upload_to='company/passport', validators=[apps_.sellers.validators.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_series', models.CharField(help_text='Passport seriyasi', max_length=10)),
                ('passport_number', models.CharField(help_text='Passport raqami', max_length=10)),
                ('jshshir', models.CharField(help_text='JSHSHIR raqami', max_length=14, unique=True)),
                ('ruyhatdan_otish_guvohnamasi_raqami', models.CharField(help_text="Ruyhatdan o'tish guvohnomasi raqami", max_length=50)),
                ('passport_image', models.FileField(help_text="Pasportning shaxsiy ma'lumotlar bilan sahifasi", upload_to='entrepreneur/passport', validators=[apps_.sellers.validators.validate_file])),
                ('inn', models.FileField(help_text="Yakka tartibdagi tadbirkor sifatida ro'yxatdan o'tganlik guvohnomasi", upload_to='entrepreneur/inn', validators=[apps_.sellers.validators.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jshshir', models.CharField(help_text='JSHSHIR raqami', max_length=14, unique=True)),
                ('ruyhatdan_otish_guvohnamasi_raqami', models.CharField(help_text="Ruyhatdan o'tish guvohnomasi raqami", max_length=50)),
                ('passport_image', models.FileField(help_text="Pasportning shaxsiy ma'lumotlar bilan sahifasi", upload_to='individual/passport', validators=[apps_.sellers.validators.validate_file])),
                ('inn', models.FileField(help_text="Yakka tartibdagi tadbirkor sifatida ro'yxatdan o'tganlik guvohnomasi", upload_to='individual/inn', validators=[apps_.sellers.validators.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerMoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference_id', models.CharField(max_length=100)),
                ('which_account', models.CharField(max_length=100)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number2', models.CharField(help_text='qushimcha telefon raqam', max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_raqami', models.CharField(default='8345279s', max_length=20, unique=True)),
                ('tasdiqlash_screenshoti_or_rasmi', models.FileField(blank=True, null=True, upload_to='shartnoma/documents', validators=[apps_.sellers.validators.validate_file])),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(default=datetime.datetime(2031, 2, 10, 16, 23, 44, 524452, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shartnoma', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['status'], name='sellers_sel_status_080ce8_idx'),
        ),
    ]
