# Generated by Django 6.0.1 on 2026-02-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('TRANSFERED_SELLER', 'Transfered to Seller'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
