# Generated by Django 6.0.1 on 2026-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0002_moneyinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyinventory',
            name='payment_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
