# Generated by Django 6.0.1 on 2026-02-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_productprice_chegirma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=29008035, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqladi', 'Tasdiqlandi'), ("to'lov amalga oshirlidi", "To'lov amalga oshirlidi"), ("to'lov kutulmoqda", "To'lov kutulmoqda"), ('yetkazilmoqda', 'yetkazilmoqda'), ('yetkazib berildi', 'Yetkazib berildi'), ('bekor qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=50)),
                ('final_quantity', models.IntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('delivery_date', models.DateField()),
                ('topshirish_punkiti', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('canceled_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product')),
            ],
        ),
    ]
