# Generated by Django 6.0.1 on 2026-02-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='topshirish_punkiti',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=13394561, max_length=20, unique=True),
        ),
    ]
