# Generated by Django 6.0.1 on 2026-02-09 15:00

import apps_.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=apps_.orders.models.create_uniqe_order_id, max_length=20),
        ),
    ]
