# Generated by Django 6.0.1 on 2026-02-09 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_id'),
        ('users', '0002_taker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.taker'),
        ),
        migrations.CreateModel(
            name='TopshirishPunktlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('sirdaryo', 'Sirdaryo'), ('jizzax', 'Jizzax'), ('nukus', 'Nukus')], max_length=200)),
                ('tuman_or_shahar', models.CharField(max_length=200)),
                ('kucha', models.CharField(max_length=200)),
                ('uy_raqami', models.CharField(max_length=200)),
                ('xonodon', models.CharField(max_length=200)),
                ('pades', models.CharField(max_length=200)),
                ('qavat', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topshirish_punktlarim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
