# Generated by Django 6.0.1 on 2026-02-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_taker_topshirishpunktlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshirishpunktlar',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topshirish_punkiti', to='orders.order'),
            preserve_default=False,
        ),
    ]
