# Generated by Django 6.0.1 on 2026-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_topshirishpunktlar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqladi', 'Tasdiqlandi'), ('tasdiqlanmoqda', 'Tasdiqlanmoqda'), ("to'lov amalga oshirlidi", "To'lov amalga oshirlidi"), ("to'lov kutulmoqda", "To'lov kutulmoqda"), ('yetkazilmoqda', 'yetkazilmoqda'), ('yetkazib berildi', 'Yetkazib berildi'), ('bekor qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=50),
        ),
    ]
