# Generated by Django 6.0.1 on 2026-01-29 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shartnoma',
            name='shartnoma_raqami',
            field=models.CharField(default='2712675s', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2031, 1, 28, 12, 30, 18, 169720, tzinfo=datetime.timezone.utc)),
        ),
    ]
