# Generated by Django 6.0 on 2026-02-02 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_shartnoma_shartnoma_raqami_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='biznes_type',
            field=models.CharField(blank=True, choices=[('individual', 'Yakka tartibdagi tadbirkor'), ('entrepreneur', "O'zini o'zi band qilgan shaxs"), ('company', 'MChJ yoki boshqa yuridik shaxs')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='shartnoma_raqami',
            field=models.CharField(default='2995799s', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2031, 2, 1, 10, 24, 53, 645111, tzinfo=datetime.timezone.utc)),
        ),
    ]
