# Generated by Django 6.0.1 on 2026-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotiontoproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiontoproduct',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotiontoseller',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
