# Generated by Django 6.0.1 on 2026-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotiontoproduct_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiontoproduct',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotiontoseller',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
