# Generated by Django 6.0.1 on 2026-01-28 12:56

import apps_.sellers.validators
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biznes_type', models.CharField(choices=[('individual', 'Yakka tartibdagi tadbirkor'), ('entrepreneur', "O'zini o'zi band qilgan shaxs"), ('company', 'MChJ yoki boshqa yuridik shaxs')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='SellerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('available_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(help_text='Hisob raqami', max_length=16, validators=[apps_.sellers.validators.validate_account_number])),
                ('bank_code', models.CharField(help_text='Bank Kodi(MFO)', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Kompaniya nomi', max_length=255)),
                ('stir', models.CharField(help_text='STIR raqami', max_length=20, unique=True)),
                ('oked', models.CharField(help_text='OKED raqami', max_length=10)),
                ('registration_certificate', models.FileField(help_text="MChJ (yoki boshqa yuridik shaxs)ni ro'yxatdan o'tkazish haqida xabarnoma yoki guvohnoma", upload_to='company/registration_certificate', validators=[apps_.sellers.validators.validate_file])),
                ('tashkilot_direktori_qarori', models.FileField(upload_to='company/tashkilot_direktori_qarori', validators=[apps_.sellers.validators.validate_file])),
                ('passport_image', models.FileField(help_text="Pasportning shaxsiy ma'lumotlar bilan sahifasi", upload_to='company/passport', validators=[apps_.sellers.validators.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_series', models.CharField(help_text='Passport seriyasi', max_length=10)),
                ('passport_number', models.CharField(help_text='Passport raqami', max_length=10)),
                ('jshshir', models.CharField(help_text='JSHSHIR raqami', max_length=14, unique=True)),
                ('ruyhatdan_otish_guvohnamasi_raqami', models.CharField(help_text="Ruyhatdan o'tish guvohnomasi raqami", max_length=50)),
                ('passport_image', models.FileField(help_text="Pasportning shaxsiy ma'lumotlar bilan sahifasi", upload_to='entrepreneur/passport', validators=[apps_.sellers.validators.validate_file])),
                ('inn', models.FileField(help_text="Yakka tartibdagi tadbirkor sifatida ro'yxatdan o'tganlik guvohnomasi", upload_to='entrepreneur/inn', validators=[apps_.sellers.validators.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_info', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jshshir', models.CharField(help_text='JSHSHIR raqami', max_length=14, unique=True)),
                ('ruyhatdan_otish_guvohnamasi_raqami', models.CharField(help_text="Ruyhatdan o'tish guvohnomasi raqami", max_length=50)),
                ('passport_image', models.FileField(help_text="Pasportning shaxsiy ma'lumotlar bilan sahifasi", upload_to='individual/passport', validators=[apps_.sellers.validators.validate_file])),
                ('inn', models.FileField(help_text="Yakka tartibdagi tadbirkor sifatida ro'yxatdan o'tganlik guvohnomasi", upload_to='individual/inn', validators=[apps_.sellers.validators.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_info', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number2', models.CharField(help_text='qushimcha telefon raqam', max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Shartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_raqami', models.CharField(default='6657817s', max_length=20, unique=True)),
                ('tasdiqlash_screenshoti_or_rasmi', models.FileField(blank=True, null=True, upload_to='shartnoma/documents', validators=[apps_.sellers.validators.validate_file])),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(default=datetime.datetime(2031, 1, 27, 12, 56, 31, 7174, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shartnoma', to='sellers.seller')),
            ],
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['status'], name='sellers_sel_status_080ce8_idx'),
        ),
    ]
