# Generated by Django 6.0.1 on 2026-01-31 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_shartnoma_shartnoma_raqami_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shartnoma',
            name='shartnoma_raqami',
            field=models.CharField(default='8007151s', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2031, 1, 30, 16, 30, 4, 641746, tzinfo=datetime.timezone.utc)),
        ),
    ]
