# Generated by Django 6.0.1 on 2026-02-05 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_seller_biznes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shartnoma',
            name='shartnoma_raqami',
            field=models.CharField(default='5431263s', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2031, 2, 4, 9, 23, 53, 321952, tzinfo=datetime.timezone.utc)),
        ),
    ]
