# Generated by Django 6.0.1 on 2026-02-14 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_shartnoma_shartnoma_raqami_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shartnoma',
            name='shartnoma_raqami',
            field=models.CharField(default='8095417s', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2031, 2, 13, 9, 21, 18, 889982, tzinfo=datetime.timezone.utc)),
        ),
    ]
