# Generated by Django 6.0.1 on 2026-02-16 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_shartnoma_shartnoma_raqami_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shartnoma',
            name='shartnoma_raqami',
            field=models.CharField(default='4845895s', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2031, 2, 15, 9, 46, 21, 15811, tzinfo=datetime.timezone.utc)),
        ),
    ]
