# Generated by Django 6.0.1 on 2026-02-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productimages_video_productvideos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='discount_price',
        ),
    ]
