# Generated by Django 6.0.1 on 2026-02-04 14:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productprice_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='reserved_quantity',
        ),
        migrations.AddField(
            model_name='productprice',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='productstock',
            name='quantity_type',
            field=models.CharField(choices=[('kilogram', 'Kilogram'), ('dona', 'Dona'), ('metr', 'Metr'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
