# Generated by Django 6.0.1 on 2026-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productstock_reserved_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='interest',
        ),
        migrations.AddField(
            model_name='productprice',
            name='chegirma',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Chegirma price - chegirms = sotiladigan summa', max_digits=10),
            preserve_default=False,
        ),
    ]
