# Generated by Django 6.0.1 on 2026-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productprice_interest_productprice_chegirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='chegirma',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Chegirma price - chegirms = sotiladigan summa', max_digits=10),
        ),
    ]
