# Generated by Django 6.0.1 on 2026-02-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_name',
        ),
    ]
